// Define your environment variables
interface Config {
    VITE_BASE_SASS_PATH: string;
    VITE_BASE_FIREBASE_API_KEY: string;
    VITE_BASE_FIREBASE_AUTH_DOMAIN: string;
    VITE_BASE_FIREBASE_DATABASE_URL: string;
    VITE_BASE_FIREBASE_PROJECT_ID: string;
    VITE_BASE_FIREBASE_STORAGE_BUCKET: string;
    VITE_BASE_FIREBASE_MESSAGING_SENDER_ID: string;
    VITE_BASE_FIREBASE_APP_ID: string;
    VITE_BASE_FIREBASE_MEASUREMENT_ID: string;
}

const config: Config = {
    VITE_BASE_SASS_PATH: import.meta.env.VITE_BASE_SASS_PATH || '',
    VITE_BASE_FIREBASE_API_KEY: import.meta.env.VITE_BASE_FIREBASE_API_KEY || '',
    VITE_BASE_FIREBASE_AUTH_DOMAIN: import.meta.env.VITE_BASE_FIREBASE_AUTH_DOMAIN || '',
    VITE_BASE_FIREBASE_DATABASE_URL: import.meta.env.VITE_BASE_FIREBASE_DATABASE_URL || '',
    VITE_BASE_FIREBASE_PROJECT_ID: import.meta.env.VITE_BASE_FIREBASE_PROJECT_ID || '',
    VITE_BASE_FIREBASE_STORAGE_BUCKET: import.meta.env.VITE_BASE_FIREBASE_STORAGE_BUCKET || '',
    VITE_BASE_FIREBASE_MESSAGING_SENDER_ID: import.meta.env.VITE_BASE_FIREBASE_MESSAGING_SENDER_ID || '',
    VITE_BASE_FIREBASE_APP_ID: import.meta.env.VITE_BASE_FIREBASE_APP_ID || '',
    VITE_BASE_FIREBASE_MEASUREMENT_ID: import.meta.env.VITE_BASE_FIREBASE_MEASUREMENT_ID || '',
};

export default config;
